Dev
vliz-be-opsci/py-RDF-store pull request #23
Opened 2024-03-20 13:34 UTC by cedricdcc

2024-03-20 13:39 UTC, bulricht commented
tests are not running

2024-03-20 13:41 UTC, cedricdcc commented
Will make a seperate branch where the tests wil run and merge it into this one once it does

2024-03-20 13:49 UTC, marc-portier requested changes
pls perform minor cleanups
for the more elaborate tests -- ok if we mark that in a follow up issue as a TODO

2024-03-20 13:49 UTC, marc-portier commented on pyrdfstore/store.py
> +        try:
are we sure we want this ? 
this hides runtime failures as it demotes them to mere log-file-entries

2024-03-20 13:49 UTC, marc-portier commented on tests/test_store.py
> +    assert True
strange, no?
maybe at least assert the query-result is not none?
or (even better) make sure the prepopulated store has triples on board that guarantee some useful response-count to be checked for?

2024-03-20 13:49 UTC, marc-portier commented on tests/test_store.py
> +    assert True
similarly - make the test more meaningful

2024-03-20 13:49 UTC, marc-portier commented on tests/test_store.py
> +    assert True
similarly - make the test more meaningful

2024-03-20 13:49 UTC, marc-portier commented on tests/test_store.py
> +
similarly - make the test more meaningful

2024-03-20 13:49 UTC, marc-portier commented on try-store.py
do we need this file? 
seems a remant of eronous local file commit
whatever it does (or did) should now be in the tests?

2024-03-20 14:59 UTC, cedricdcc commented on try-store.py
No general purpose anymore , so deleted

2024-03-21 09:50 UTC, marc-portier commented on tests/conftest.py
> +    if read_uri is not None:
lines 20 to 23 are unreachable and make no more sense -- @cedricdcc please remove this historic glitch before merge

2024-03-21 13:59 UTC, marc-portier commented on tests/test_store.py
> +from util4tests import run_single_test
should also import log
```python
from util4tests import run_single_test, log
```

2024-03-21 14:00 UTC, marc-portier commented on tests/test_store.py
> +log = getLogger("tests")
should not be redefined here but imported from `util4tests`

2024-03-22 08:42 UTC, merged